#Nombre del workflow

name: Build de Angular app

# Disparadores de este workflow/pipeline. Se pueden definir sobre que ramas queremos hacerlo.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Inicia la cadena de montaje
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Instalar Node
        uses: action/setup-node@v1
        with:
          node-version: 12.8
          
      - name: Instalar dependencias/modulos
        run: npm install
      
      - name: Build/Ejecutar
        run: npm run build -- --prod
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      


